env:
  browser: true
  node: true
  es2021: true
  'jest/globals': true
extends:
  - 'plugin:react/recommended'
  - 'eslint:recommended'
  - 'plugin:react/jsx-runtime'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - jest
  - prettier
rules:
  'prettier/prettier': 'error'
settings:
  react:
    version: detect
